package com.yunbiao.armyface_offline.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig signDaoConfig;
    private final DaoConfig userDaoConfig;

    private final SignDao signDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        signDaoConfig = daoConfigMap.get(SignDao.class).clone();
        signDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        signDao = new SignDao(signDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Sign.class, signDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        signDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public SignDao getSignDao() {
        return signDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
